### ISSUE TITLE
useCommon `inc` and `dec` types are incorrect

### ISSUE THREAD

**Issue by brandonpittman** [kyleshevlin/use-common#1]
https://github.com/kyleshevlin/use-common/blob/4e724e1f3dcdab07fc117cd915392ee544e30448/src/useCounter.tsx#L5-L6

Forgive me if I'm missing something, but it seems like these types should have no params, while the types say they require a number.

**Comment by kyleshevlin** [comment]
Good catch, surprised the type checker didn't say anything about it. Fixed in #2
